image: Visual Studio 2017

platform: 
  - x64
  - x86

configuration:
  - Release
  
environment:
  MSVC_VERSION: 15

install:
  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  
before_build:
  # Run cmake
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G "CodeBlocks - Ninja" -DCMAKE_BUILD_TYPE=%configuration% ..\expat
  
build_script:
  - cmake --build . --target all --config %configuration%
    
test_script:
  - cp expatd.dll tests\
  - tests\runtests.exe
